Feature/io 751 actions
ekaterina-demeshko-idf/star_movie_app pull request #13
Opened 2022-10-26 16:29 UTC by ekaterina-demeshko-idf

2022-10-26 16:32 UTC, nikolay-ahramovich-idf approved these changes

2022-10-26 18:48 UTC, andrei-lastochkin-idf approved these changes

2022-10-27 07:37 UTC, sergei-mikhailovskii-idf requested changes

2022-10-27 07:37 UTC, sergei-mikhailovskii-idf commented on android/app/build.gradle
> +//    ndkVersion flutter.ndkVersion
delete comment

2022-10-27 07:37 UTC, sergei-mikhailovskii-idf commented on android/build.gradle
> +    ext.kotlin_version = '1.5.30'
why did u downgrade the version? use 1.6.10 at least. or even better 1.7.20

2022-10-27 08:29 UTC, ekaterina-demeshko-idf commented on android/build.gradle
> +    ext.kotlin_version = '1.5.30'
traces of desperate attempts to make it work

2022-10-27 09:17 UTC, sergei-mikhailovskii-idf approved these changes

2022-10-27 10:51 UTC, merged