add validation exception
ekaterina-demeshko-idf/star_movie_app pull request #14
Opened 2022-10-27 12:05 UTC by ekaterina-demeshko-idf

2022-10-27 12:09 UTC, nikolay-ahramovich-idf approved these changes

2022-10-27 12:13 UTC, andrei-lastochkin-idf approved these changes

2022-10-27 12:13 UTC, andrei-lastochkin-idf commented on packages/domain/lib/usecase/check_user_usecase.dart
> +    if (!(await _firestoreRepository.checkUserExist(user))) {
I'd move await _firestoreRepository.checkUserExist(user) to separate var

2022-10-27 12:15 UTC, ekaterina-demeshko-idf commented on packages/domain/lib/usecase/check_user_usecase.dart
> +    if (!(await _firestoreRepository.checkUserExist(user))) {
it is void method

2022-10-27 12:21 UTC, ekaterina-demeshko-idf commented on packages/domain/lib/usecase/check_user_usecase.dart
> +    if (!(await _firestoreRepository.checkUserExist(user))) {
а ой

2022-10-27 14:59 UTC, sergei-mikhailovskii-idf requested changes

2022-10-27 14:59 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login_bloc.dart
> +        await _checkUserUseCase(user);
validation usecase should also be called in try block

2022-10-27 16:28 UTC, sergei-mikhailovskii-idf requested changes

2022-10-27 16:28 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login_bloc.dart
> +      if (_formKey.currentState?.validate() ?? false) {
still not good - u should call form.validate only in the catch block. it shouldn't be in try

2022-10-28 11:37 UTC, sergei-mikhailovskii-idf requested changes

2022-10-28 11:37 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/login_validation_usecase.dart
> +    if (emailFailedType != null && passwordFailedType != null) {
what if only email/password is incorrect ...

2022-10-28 11:51 UTC, sergei-mikhailovskii-idf approved these changes

2022-10-28 11:52 UTC, merged